Feature ts
TechLabGroup/DuesCalculateApp pull request #1
Opened 2017-08-15 03:04 UTC by taninoBiz

変更点は２点
・飲み会作成画面から一覧画面へのモーダルを閉じるボタン追加
・飲み会TBLの作成と、一覧画面へテスト的な呼出コードを記載

2017-08-15 03:30 UTC, nagasakiTechLab requested changes
見ました。
たぶんPartyTableがPJに追加されてないのが主要因だと思いますが、コメントの点も修正した方がいいと思います。

2017-08-15 03:30 UTC, nagasakiTechLab commented on DuesCalculateApp/Model/DB/PartyTable.swift
> +    dynamic var partyId = Int() //飲み会ID
Realmのオブジェクトは初期化せずに型宣言だけしとくのがよいですね。
`dynamic var partyId: Int`
みたいな形です。
初期値与えるなら
`dynamic var partyId: Int = 0`
とか。

2017-08-15 03:30 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyAdd/PartyAddViewController.swift
> +        func tapCloseButton() {
インデントずれとるよ

2017-08-15 03:30 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyListViewController.swift
> +        let testTitle = realm.objects(PartyTable.self).first
`.self`必要だっけ？

2017-08-15 03:30 UTC, nagasakiTechLab commented on DuesCalculateApp/Model/DB/PartyTable.swift
> +final class PartyTable: Object {
Realmオブジェクトのクラス名にTableは不要かな

2017-08-17 08:01 UTC, taninoTechLab commented on DuesCalculateApp/View/PartyList/PartyListViewController.swift
> +        let testTitle = realm.objects(PartyTable.self).first
警告が出てたので追加しました。

2017-08-17 08:30 UTC, taninoTechLab commented
@nagasakiTechLab 修正してテストコードが稼働したのであげ直しました！

2017-08-17 10:31 UTC, closed without merging