Feature/party add view
TechLabGroup/DuesCalculateApp pull request #3
Opened 2017-08-31 08:52 UTC by taninoTechLab

飲み会一覧画面
・カスタムセルで開催日を表示
・削除ボタンを追加、削除機能

2017-09-04 10:24 UTC, nagasakiTechLab requested changes
Swift上達してるようで何より。
コメント参照で対応お願いします。

2017-09-04 10:24 UTC, nagasakiTechLab commented on DuesCalculateApp/Model/DB/DBManager.swift
> +        return party
Realmの世界観は/Modle/DBの中だけに留めておくべきなので、 `return Array(party)` で単なる配列にして返してあげる方がよい

2017-09-04 10:24 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyAdd/PartyAddViewController.swift
> +        let totalAmount: Int? = Int(inputTotalAmount.text!)
`: Int?` は不要なはず

2017-09-04 10:24 UTC, nagasakiTechLab commented on DuesCalculateApp/Model/DB/DBManager.swift
> +    public func deleteParty(party: Results<Party>, indexId: Int) {
ここも同じく、引数にResults型を持たない。
再検索してから削除かな。

2017-09-04 10:24 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyAdd/PartyAddViewController.swift
> +    func tapCloseButton() {
公開範囲はprivateでいいと思う。ただ `#selector` の対象にしているので、 `@objc` のキーワードもつける必要があります。まとめると以下です。
```
@objc private func tapCloseButton() {
```

2017-09-04 10:24 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyAdd/PartyAddViewController.swift
> +        let _: Bool = DBManager().createParty(partyName: partyName!, partyDate: partyDate!, totalAmount: totalAmount!)
値精査をしたら `!` によるforceUnwrappingは不要になるはずですが、忘れないようにコメントで `// TODO: 精査後要修正` を書いておいてください。

2017-09-04 10:24 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyAdd/PartyAddViewController.swift
> +    func tapCloseButton() {
PartyListViewControllerの横並び確認もお願いします

2017-09-04 10:24 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyListViewController.swift
> +            DBManager().deleteParty(party: object, indexId: indexPath.row)
indexPath.rowでレコード特定するなら少なくともsearchPartyおよびdeletePartyで、レコード検索結果のsort指定はするべきですね。

2017-09-04 10:24 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyListViewController.swift
> +            DBManager().deleteParty(party: object, indexId: indexPath.row)
ほんとはキーであるIDとかで指定するべき。検討してみてください。

2017-09-08 07:54 UTC, taninoTechLab commented
@nagasakiTechLab 
指摘対応しました！再確認お願いしますー

2017-09-11 11:04 UTC, nagasakiTechLab requested changes
確認しました。まだ修正必要です。

2017-09-11 11:04 UTC, nagasakiTechLab commented on DuesCalculateApp/Model/DB/DBManager.swift
> +            realm.delete(party[partyId])
party[]の中に入る数字って単なる順番ですよね？
Idと順番はイコールではないですね。
42行目で検索結果をpartyIdでfilterしてください。

2017-09-11 11:04 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyListViewController.swift
> +        parties = DBManager().searchParty()
DBManagerインスタンス化しまくってたんですね。
DBManagerのファンクションはstaticにしましょう。

2017-09-11 11:04 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyListViewController.swift
> +    var parties: [Party]!
`!` は基本的に使わないようにしましょう。
めんどくさくてもオプショナル（ `?` ）にしてください。

2017-09-11 11:04 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyTableViewCell.swift
> +    var partyId: Int = 0
ここもめんどくさくてもオプショナルにするべき。初期値0に意味がない。

2017-09-12 08:34 UTC, nagasakiTechLab requested changes
コメント参照ください

2017-09-12 08:34 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyListViewController.swift
> +        return parties!.count
`!` は避けましょう。↓こんな感じで万が一nullだったときの値を設定してあげればよい（詳しくは本日のSwift勉強会で高崎くんが教えてくれるはずｗ）
```
return parties?.count ?? 0
```

2017-09-12 08:34 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyListViewController.swift
> +        cell.partyId = (parties?[indexPath.row].partyId)!
partyIdをオプショナルで宣言してるので `!` しなくてもいいはず

2017-09-12 08:34 UTC, nagasakiTechLab commented on DuesCalculateApp/View/PartyList/PartyTableViewCell.swift
> +    @IBOutlet weak var partyName: UILabel?
@IBOutletは元から `!` で宣言されてると思うのでそのままで大丈夫です

2017-09-12 08:34 UTC, nagasakiTechLab commented on DuesCalculateApp/Model/DB/DBManager.swift
> +    static public func createParty(partyName: String, partyDate: String, totalAmount: Int) -> Bool {
一般的には public static の順番ですね（public static void main的に考えて）

2017-09-12 11:35 UTC, nagasakiTechLab approved these changes

2017-09-12 11:36 UTC, nagasakiTechLab commented
OKです！

2017-09-13 00:04 UTC, merged