Feature/party detail
TechLabGroup/DuesCalculateApp pull request #4
Opened 2017-09-15 02:42 UTC by YusukeUenaka

・飲み会詳細画面のボタン押下時にダイアログを表示
・NavigationBarの「＋」とタイトルを表示。「＋」押下時に精算者選択画面に遷移
・TableViewパーツを配置
・PartyDetailのRealmを追加

2017-09-25 01:58 UTC, takuto1212 requested changes
確認しました。確認お願します。

2017-09-25 01:58 UTC, takuto1212 commented on DuesCalculateApp/Model/DB/PartyDetailMember.swift
> +        return "partyId"
確認です。
このクラスのpartyIはPartyクラスのpartyIdと同じですか？
partyIdが主キーであっていますか？
そうだとすると参加者がString型だと一人しか登録できなくないですか？

2017-09-25 01:58 UTC, takuto1212 commented on DuesCalculateApp/View/PartyDetail/PartyDetailViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: UIBarButtonSystemItem.add, target: self, action: #selector(editMember) )
型予測できるので、
UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(editMember) )
で書けます。

2017-09-25 01:58 UTC, takuto1212 commented on DuesCalculateApp/View/PartyDetail/PartyDetailViewController.swift
> +    @IBAction func alertPush(_ sender: UIButton) {
谷野さん、佐藤さんにも指摘していますが、
メソッドやプロパティのコメントを書くようにしましょう。
※searchPartyがオーバーロードしてあるので、違いを明確にした方があとで迷わないです。

行にカーソルをあわせて
alt + command + / でコメントのフォーマットが自動で入れることができます。

/// <#Description#>
///
/// - Parameter partyId: <#partyId description#>
/// - Returns: <#return value description#>
public static func searchParty(partyId: Int) -> [Party] {

2017-09-25 01:58 UTC, takuto1212 commented on DuesCalculateApp/Model/DB/PartyDetailMember.swift
> +    dynamic var partyId = Int() //飲み会ID
初期化の方法を他と合わせましょう。

https://github.com/TechLabGroup/DuesCalculateApp/blob/feature/PartyUpdate/DuesCalculateApp/Model/DB/Party.swift

2017-10-16 03:10 UTC, YusukeUenaka commented on DuesCalculateApp/View/PartyDetail/PartyDetailViewController.swift
> +    @IBAction func alertPush(_ sender: UIButton) {
承知しました。追記していきます。

2017-10-16 03:10 UTC, YusukeUenaka commented on DuesCalculateApp/View/PartyDetail/PartyDetailViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: UIBarButtonSystemItem.add, target: self, action: #selector(editMember) )
指摘内容に修正いたしました。

2017-10-16 03:10 UTC, YusukeUenaka commented on DuesCalculateApp/Model/DB/PartyDetailMember.swift
> +        return "partyId"
主キーは、Partyクラス用の主キーを個別で用意します。丸山さんと合意済みです。

2017-10-16 03:10 UTC, YusukeUenaka commented on DuesCalculateApp/Model/DB/PartyDetailMember.swift
> +    dynamic var partyId = Int() //飲み会ID
修正いたしました。

2017-10-25 04:04 UTC, YusukeUenaka commented
・飲み会詳細画面のボタン押下時にダイアログを表示
・NavigationBarの「＋」とタイトルを表示。「＋」押下時に精算者選択画面に遷移
・TableViewパーツを配置
・PartyDetailのRealmを追加

2017-10-25 04:06 UTC, YusukeUenaka commented
スイッチボタン押下でフラグとセルの背景、集計結果の表示を変更する処理を追記。

2017-10-25 09:40 UTC, merged